[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMonoNLNerdFontMono", style = "Thin" }
size = 13.0

[selection]
save_to_clipboard = true
